### ISSUE TITLE
Automatically start test when user clicks "Test Speed"

### ISSUE THREAD

**Issue by nkinkade** [m-lab/bq2geojson#108]
Right now, a user clicks the "Test Speed" button in the interface which takes them to a place where they must them launch the test by clicking another button.  That intermediate step should probably be removed since we already know they want to run the test once they click the "Test Speed" button on the introduction page.

**Comment by critzo** [comment]
Because we're folding bq2geojson into piecewise, copied this issue to: 
https://github.com/opentechinstitute/piecewise/issues/66
Closing
