### ISSUE TITLE
#mobile-menu is showing above 500px wide

### ISSUE THREAD

**Issue by gembarrett** [m-lab/bq2geojson#112]
Reproduce:
1. reduce browser width so iframe is ~500px wide

Expected outcome:
1. default desktop view at bottom of screen: timeline bar, play button, speed and year options, legend

Actual outcome: 
1. three lines are shown to the right of the timeline bar
<img width="101" alt="screen shot 2016-02-09 at 10 38 50" src="https://cloud.githubusercontent.com/assets/949948/12921037/55f7f254-cf19-11e5-993b-d4f647a989a6.png">

Fix: 
1. Hide div #mobile-menu until needed

**Comment by gembarrett** [comment]
will technically be dealt with temporarily by #114

**Comment by critzo** [comment]
Resolved for V1 Launch in #114. Updating milestone to v2

**Comment by critzo** [comment]
Because we're folding bq2geojson into piecewise, copied this issue to: 
https://github.com/opentechinstitute/piecewise/issues/65
Closing
