### ISSUE TITLE
"Download" is under the text box for input

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/bq2geojson#113]
![screen shot 2016-02-08 at 9 57 28 pm](https://cloud.githubusercontent.com/assets/941210/12921161/d8c94b92-cf19-11e5-8952-08904e810079.png)

**Comment by gembarrett** [comment]
Which browser or device is this?

**Comment by georgiamoon** [comment]
On Chrome on Mac. I think it's only at certain widths (some of the middle sizes), but not exactly sure.

**Comment by critzo** [comment]
@georgiamoon @gembarrett This [commit](https://github.com/opentechinstitute/bq2geojson/commit/436594c6968005a8b77c2e662910f6cb3d73641d) should resolve this issue. Can you please confirm?
http://files.opentechinstitute.org/~critzo/mlab/collab/seattle/broadband/broadband-speed-tes

**Comment by gembarrett** [comment]
Still occurs in Chrome at ~720-760px

**Comment by critzo** [comment]
Huh. I'm not seeing it on my test mac.

**Comment by gembarrett** [comment]
I'm confused by the fact it's fine in Firefox as well. Hmm

**Comment by critzo** [comment]
Fernanda just tested on Mac OS using Chrome and Safari, and things look fine. She is downloading Firefox to test it there as well. Just to confirm, you are looking at the page from files.opentechinstitute.org, right?

**Comment by critzo** [comment]
Fernanda confirms this looks ok on Firefox for Mac as well.
