### ISSUE TITLE
Year/month/metrics selectors don't work on nexus 6

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#114]
When browsing the map on a nexus 6 Android phone, the metrics and date selectors are displayed but nothing happens when attempting to click on them

**Comment by gembarrett** [comment]
I also saw this on iPhone, it's a mobile issue that must be fixed

**Comment by gembarrett** [comment]
related? https://github.com/mapbox/mapbox.js/issues/733

**Comment by gembarrett** [comment]
when you tap on the dropdown it also taps on the map - we need to separate the two

**Comment by gembarrett** [comment]
Taking those controls out of the map results in them working - confirms there's interference coming from the map element

**Comment by gembarrett** [comment]
Temp workaround for launch is to hide the mobile menu - just state what data is being shown e.g. "Data shown is download speeds from January - February 2016"

**Comment by gembarrett** [comment]
Potential future workaround is to use duplicated controls which then copy values across to those linked with the map

**Comment by gembarrett** [comment]
Also show legend

**Comment by critzo** [comment]
Per Bruce's feedback on the 2/9 check-in, for small screen widths (below 700), we will replace the current controls with the legend and text:
"Showing _metric_ from _month_, _year_"

**Comment by gembarrett** [comment]
$('#selectMetric').val()

**Comment by critzo** [comment]
@gembarrett I went ahead and pulled these changes into the piecewise branch and updated Linode. If you are working more this evening, I'm not seeing the text in the bottom bar, but the controls are being hidden, so that should suffice for launch.

**Comment by gembarrett** [comment]
fixed it, forgot to change branch though so I've ended up reopening the 114-mobile-metrics-workaround branch and all should work fine now.

**Comment by critzo** [comment]
Merged into piecewise branch. Thanks @gembarrett . Changing this issue to v2 milestone and we'll continue to work on the workaround for functional controls on mobile.

**Comment by critzo** [comment]
Because we're folding bq2geojson into piecewise, copied this issue to: 
https://github.com/opentechinstitute/piecewise/issues/55
Closing
