### ISSUE TITLE
Mobile menu show hide scales too small 

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#116]
On mobile, nexus 6, the hamburger menu controlling show hide of the controls, scales too small in landscape view and floats left when controls are hidden. Should be a little larger and float right.

**Comment by gembarrett** [comment]
Can we have a screenshot please?

**Comment by gembarrett** [comment]
Added low priority for now as sounds like still accessible, escalate if not

**Comment by critzo** [comment]
duplicate of #112 closing
