### ISSUE TITLE
Very difficult to get out of zoom

### ISSUE THREAD

**Issue by gembarrett** [m-lab/bq2geojson#118]
Zooming automatically happens when filling out form, but when going to the map it becomes very difficult to zoom back out again.

iPhone 6S, Safari

Proposed fix: prevent zooming (will mean that nothing else should require zooming for interaction)

**Comment by gembarrett** [comment]
Zoom already disabled. Should investigate zooming back out after inputs lose focus.

**Comment by critzo** [comment]
Fernanda just tested for this issue on an iPhone 5c. 
The zooming behavior for filling out the form fields works fine. 
Double tapping the map zooms in, and pinch in/out to zoom in/out works as well. Fernanda said the controls were a little touchy here, but not a blocking issue. 

It might be worth discussing a little more or testing on a newer iPhone? or we could shelve this to v2 
@georgiamoon @gembarrett thoughts?

**Comment by critzo** [comment]
Moving to v2 milestone.

**Comment by critzo** [comment]
Because we're folding bq2geojson into piecewise, copied this issue to: 
https://github.com/opentechinstitute/piecewise/issues/64
Closing
