### ISSUE TITLE
Test button is too small and weirdly styled

### ISSUE THREAD

**Issue by gembarrett** [m-lab/bq2geojson#119]
![slack_for_ios_upload-1 png](https://cloud.githubusercontent.com/assets/949948/12922543/e9722562-cf1f-11e5-8b4e-17e44d4fa50f.jpeg)

**Comment by gembarrett** [comment]
iPhone 6S, Safari

**Comment by critzo** [comment]
Because we're folding bq2geojson into piecewise, copied this issue to: 
https://github.com/opentechinstitute/piecewise/issues/63
Closing
