### ISSUE TITLE
Font change on menu bar and form. 

### ISSUE THREAD

**Issue by fernandalavalle** [m-lab/bq2geojson#121]
Using Mac and Chrome 48.0. 

When I first load http://files.opentechinstitute.org/~critzo/mlab/collab/seattle/broadband/broadband-speed-test, the font on the menu bar and the form seems larger than its supposed to and running over. 
![toobigmenu](https://cloud.githubusercontent.com/assets/3836867/12924027/1a015c9c-cf26-11e5-8165-3e8448925fb1.png)

But when I navigate to http://www.seattle.gov/broadband-speed-test-about and then click back, the font seems to be fixed. 

![fixedmenu](https://cloud.githubusercontent.com/assets/3836867/12924041/2dced178-cf26-11e5-9701-4edd6dbd882a.png)

**Comment by gembarrett** [comment]
Not for us - it's a copy of Seattle's site that's around our map.
