### ISSUE TITLE
Not being asked to share location

### ISSUE THREAD

**Issue by gembarrett** [m-lab/bq2geojson#122]
on iPhone 6S I'm not actually getting asked to share my location - might just be my settings though - can others confirm they're being asked to share location on mobile please?

**Comment by gembarrett** [comment]
Confirmed by @critzo "I sometimes have to restart a browser session to see the location prompt"

**Comment by critzo** [comment]
Because we're folding bq2geojson into piecewise, copied this issue to: 
https://github.com/opentechinstitute/piecewise/issues/62
Closing
