### ISSUE TITLE
investigate cross browser geolocation

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#123]
Iceweasel (and potentially other browsers) does ask for your location, but does not provide the text about "searching from: " that is displayed in Chrome. Look at which geolocation features need to be enabled for which browsers

**Comment by gembarrett** [comment]
Linked to #122

**Comment by critzo** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=726230

**Comment by critzo** [comment]
Because we're folding bq2geojson into piecewise, copied this issue to: 
https://github.com/opentechinstitute/piecewise/issues/62
Closing
