### ISSUE TITLE
feed a different polygon file in to join to the m-lab data

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/bq2geojson#16]
It'd be useful to be able to feed a different geosjon layer, e.g. council districts and join the data so that we have median values by district

I started to look at http://turfjs.org/static/docs/module-turf_median.html as a way to do it, but just didn't have time to finish it today.

**Comment by nkinkade** [comment]
Using any set of arbitrary polygons should be really easy to incorporate, and pretty much zero work with regard to Turf.js.   Finding or producing the set of polygons seems like more of a challenges.

**Comment by georgiamoon** [comment]
There are lots that exist already (e.g. districts, census tracts, etc). Would it be possible to feed in a shapefile? or does turf need geo/topojson?

**Comment by nkinkade** [comment]
With the latest commits, this feature is now implemented.  Closing.
