### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#19]
"You're approximate location" should be "Your approximate location"

**Comment by nkinkade** [comment]
Fixed in commit @b7edc47 ... it hasn't been merged back to the main piecewise branch, but presumably will be soon.

**Comment by critzo** [comment]
That branch (piecewise-css) has a number of other changes that probably
shouldn't be merged, so my sense is that we should abandon that branch
and fix issue #19 in a different feature branch.

branch piecewise-css also shows that a number of other files are being
tracked that maybe shouldn't be. What do you think @nkinkade ?

**Comment by gembarrett** [comment]
It's fixed on my branch timeline-ui-tweaks so can just bring that in to deal with the issue

**Comment by nkinkade** [comment]
Oops.  I just committed a fix to the piecewise branch @501f9e1.  When we go to merge those may conflict, but should be trivial to resolve manually.  In any case, I think we can safely leave this issue closed.
