### ISSUE TITLE
adjust color scheme for map legend and overlay colors

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#29]
The map legend and shape overlay colors should be adjusted using the suggestions below from the City of Seattle:
- Dark green. Two or more gigabit providers observed (Download speed > 900mbps)
- Light green. One or more providers observed (Download speed >900mbps)
- Light yellow. Two or more providers observed providing broadband (Download speed >20mpbs)
- Yellow. One or more providers observed providing broadband internet service (Download speed >20mbps)
- Light red. One or more providers observed providing internet service (Download speed >7mpbs)
- Red. No providers providing atleast 7mbps internet service. (Download speed < 7mbps)

**Comment by gembarrett** [comment]
light yellow is too light to be visible (even tried lightgoldenrodyellow and removed opacity on the legend colours) so maybe need to rethink that. 

Also the order of colours is a bit confusing. We seem to be going full colour, light colour, light, full, light, full. Wondering if light yellow and yellow should be swapped around?

Think I may need some guidance on how we're picking up the "two or more providers" data too, not clear from initial inspection of the javascript.

**Comment by critzo** [comment]
The color spec above is copied verbatim from Seattle's original documentation, and I think we can just consider it a guideline. As long as we use colors that work for readability we'll be ok. 

On the  ISPs/providers, we aren't pulling in that data currently. The M-Lab data shows a bit of the ISP info, which we can query via the piecewise API and get json back, but it's incomplete. 

I think we should add a field to the post-test form for "Who is your ISP?"-- that way Seattle can start to get this data directly from users.

**Comment by georgiamoon** [comment]
Do these colors work for colorblindness? Probably something we should check!

**Comment by critzo** [comment]
@georgiamoon good call. we should use colors that work for colorblindness

**Comment by gembarrett** [comment]
This site has a tool showing what a webpage or image looks like to those with different types of colour blindness http://www.vischeck.com/vischeck/vischeckImage.php - could be handy for testing the visibility

**Comment by critzo** [comment]
I ran a screen grab of the map through this site and attached are the results. I think we're ok. Others may wish to review/confirm.
Original:
![orig](https://cloud.githubusercontent.com/assets/4633345/9450764/8f410058-4a78-11e5-891a-4e35a27f030b.jpg)

![deuteranope-red-green-check](https://cloud.githubusercontent.com/assets/4633345/9450778/9ee79774-4a78-11e5-9f11-fe9e5f765fc8.jpg)
![protanope-red-green-check](https://cloud.githubusercontent.com/assets/4633345/9450754/820f5b8c-4a78-11e5-835e-d2044ae3b967.jpg)
![tritanope-blue-yellow-check](https://cloud.githubusercontent.com/assets/4633345/9450753/820782fe-4a78-11e5-8baa-731503a3953d.jpg)
