### ISSUE TITLE
Provide city level summary data

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#31]
Per [city requirement 3.3](https://github.com/openseattle/seanetmap/wiki/Requirements-from-the-City-of-Seattle%2C-Annotated#cityreq33), somewhere in the UI we need a city-level summary showing performance by provider with the following:
- Median Download Speed
- Median Upload Speed
- Mean Latency (RTT)
- Diurnal graph showing performance by time of day

**Comment by critzo** [comment]
The last bit about performance by time of day might also include the same by provider to meet the similar piece in https://github.com/m-lab/bq2geojson/issues/30

**Comment by critzo** [comment]
Piecewise provides some aggregation by ISP from M-Lab data, but it's not complete and lists too few ISPs. This could be due to not enough or incorrect data from maxmind that is brought in by Telescope, or it could be that the Maxmind data is not updated. In any case, we have all the data listed in the requirement except for the hour/by/hour graph of data by time of day. @nkinkade can we parse the json returned for each area into a graph showing each metric by time of day?

**Comment by critzo** [comment]
The issue with ISPs not being included has been resolved. This query of the stats endpoint provides JSON suitable for summary level data by ISP by month:

http://45.79.197.214/stats/q/by_census_block?format=json&stats=AverageRTT,DownloadCount,MedianDownload,AverageDownload,UploadCount,MedianUpload,AverageUpload&b.isp_bins&b.spatial_join=key&b.isp_bins&b.time_slices=month

See more about the time slices available here: 
https://github.com/opentechinstitute/piecewise/blob/master/README.md#bin-types

**Comment by georgiamoon** [comment]
Sweeeeeeeeeet.

On Wed, Sep 16, 2015 at 10:47 AM, critzo notifications@github.com wrote:

> The issue with ISPs not being included has been resolved. This query of
> the stats endpoint provides JSON suitable for summary level data by ISP by
> month:
> 
> http://45.79.197.214/stats/q/by_census_block?format=json&stats=AverageRTT,DownloadCount,MedianDownload,AverageDownload,UploadCount,MedianUpload,AverageUpload&b.isp_bins&b.spatial_join=key&b.isp_bins&b.time_slices=month
> 
> See more about the time slices available here:
> 
> https://github.com/opentechinstitute/piecewise/blob/master/README.md#bin-types
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/bq2geojson/issues/31#issuecomment-140764027.

## 

Georgia Bullen
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon

**Comment by critzo** [comment]
@georgiamoon is working on this in the charts branch
