### ISSUE TITLE
add "ISP" as a select list in the post-test form

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#42]
per #41, we need to have users select their ISP in the post test form since we don't have good enough data in M-Lab/Maxmind to aggregate test data by ISP.

**Comment by georgiamoon** [comment]
Can we pre-populate a list of the known ISPs and then provide an other
category if the user's ISP isn't listed? My concern here is just that the
data that people enter is likely to be messy, so if we can make it
clean-ish, we make it easier to analyze/feed stats elsewhere on the site.

**Comment by critzo** [comment]
@georgiamoon absolutely. I'm seeing this as a select list with known ISPs, not a text box entry for that very reason.

**Comment by georgiamoon** [comment]
Sounds great.

We should allow for an "other" with a text entry, just in case.

**Comment by critzo** [comment]
@georgiamoon @gembarrett @nkinkade 
I added a select form with a start on the javascript to show a "other" text option when other is selected in the isp list: https://github.com/m-lab/bq2geojson/commit/1cc8405e2f1d46448e8eb789529cad963a4b4eb5 

My JS skills are rudimentary though. Could one of you review? Thanks.

**Comment by critzo** [comment]
this is fixed with https://github.com/m-lab/bq2geojson/commit/a7cf12b780a6250eb45ddd8373a9b9eafc85ec05
