### ISSUE TITLE
Have an option layer of the point data from the tests

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/bq2geojson#5]
Building on how we prototypes this..
- Data would need to be scattered additionally (to avoid overlapping points) and/or aggregated to make clear when all coming from one IXP/ASN
- Could be points and routes some day (allow for pathing where we have data available)

**Comment by nkinkade** [comment]
What do you mean by "option layer"?  Is this just a suggestion for some possible improvements to the existing "scatter plot" layer?

**Comment by georgiamoon** [comment]
Typo sorry - "optional." 

I think you actually covered this already. I was just wanting to document that we know we need to do something to the data to make it more representative rather than the X,Ys that come from BQ.

**Comment by nkinkade** [comment]
Closing ticket.  Scatter plot layer is already present and configurable, but may at some future point need to be adjusted to compensate for the low quality of the geo data we have for tests.
