### ISSUE TITLE
Collapse layer control by default?

### ISSUE THREAD

**Issue by nkinkade** [m-lab/bq2geojson#52]
We might consider collapsing the layer control by default.  It will save space, especially on mobile devices.  Especially with only one base layer to select from, the only reason to have it there is make it obvious to a user that they can view stats by council district:

https://github.com/m-lab/bq2geojson/blob/piecewise/html/index.html#L354

Close this ticket if this isn't a good idea.

**Comment by georgiamoon** [comment]
@gembarrett and I were talking about this. Agreed.

**Comment by critzo** [comment]
I also added this to hide the basemap control and separator when it's expanded:
https://github.com/m-lab/bq2geojson/commit/73ee957d26d344c0589fcaad5fbc8314eaf41385

**Comment by gembarrett** [comment]
Added to mobile-menu so collapsed by default (along with location and legend).
