### ISSUE TITLE
hide legend and timeline on small screens when other tabs are open

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#59]
On small screens like my phone , the legend, timeline and top bar get in the way of the test tab, post test form and about page content. 

for small screens we should consider closing/hiding these elements when the right side tabs are open.

**Comment by gembarrett** [comment]
Similar design/layout to initial load (no bottom bar, sidebar, etc) - just add a dismiss button

**Comment by critzo** [comment]
Let's plan to revisit this issue as a future feature, or if Seattle brings up the issue.
