### ISSUE TITLE
play button doesn't stop playing

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/bq2geojson#62]
Maybe it's just mine? But it keeps playing even when I pause it.

**Comment by critzo** [comment]
This wasn't happening for me. Georgia was using Chrome on Mac. @gembarrett let's look for this in browser testing (#66)

**Comment by critzo** [comment]
Because we're folding bq2geojson into piecewise, copied this issue to: 
https://github.com/opentechinstitute/piecewise/issues/68
Closing
