### ISSUE TITLE
Post-test submission form should have javascript validation

### ISSUE THREAD

**Issue by nkinkade** [m-lab/bq2geojson#68]
Piecewise implements some basic backend validation for data submitted by users after a speed test has  been run, but it's only sufficient to make sure no spurious data ends up in the database.  The frontend should also implement some basic validation.  I'm not sure what that validation looks like, since I'm not sure what Seattle thinks on that front.  Some things that occur to me:
- There is a hidden form field, bigquery_key, which gets populated by javascript after the test is run.   In the event that that field isn't populated, does Seattle still want the data recorded, even if it can't be correlated with an actual test?
- What if someone enters, say, 5000 in the advertised up/down boxes (clearly bogus)?  Should that value still be submitted?  That is, should there be an upper or lower bound on values that will be considered for submission.  
- Same as above for cost of service?  Should the value be bounded?

There may be other things Seattle wants to check for, such as don't as don't accept field X if field Y has no value, etc.

**Comment by critzo** [comment]
I think we should make the call on frontend validation for Seattle. They may have some feedback once their security people test the form, and we can also ask this question to confirm what they want, but at a minimum, if the test is not completed I don't see any reason to store a record in extra_data. @georgiamoon @gembarrett any other thoughts?

Another question - Map aggregation only uses the HTML5 geolocation in the extra_data table rows, yes?

**Comment by nkinkade** [comment]
Map aggregation uses the lat/lon in the extra_data table, if it exists for a given test, otherwise it falls back on the lat/lon provided by our MaxMind data.
