### ISSUE TITLE
Integrate NDT test to allow a user to run their own test

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/bq2geojson#7]
- could leverage HTML Geolocation to improve lat/lon quality
- should then show the user's data point on the map with the layers from M-Lab and other public datasets
- allow for a user to include information about their internet connection, e.g. type of location (home, business, coffeeshop, etc), type of connection (residential, commercial), known costs (optional), etc.

See notes from @alyssa-smith's work:
https://docs.google.com/a/opentechinstitute.org/document/d/1x5h7r1wX1myKJk0UFz-uB_nh_c75KglOU0ZyOxWzTlM/edit

**Comment by nkinkade** [comment]
Basic implementation done in @c8c4eaf, just needs to be made pretty.  Closing
