### ISSUE TITLE
Turn off scroll to zoom on the map

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/bq2geojson#70]
Particularly because of the iframe size on the Seattle page, let's turn off scroll to zoom so that users don't get trapped in the map zooming and can get to the controls.

**Comment by gembarrett** [comment]
Hmm I've got some usability concerns about removing this default and expected interaction - not seen it interfere with the controls so far, can we chat about this?

**Comment by georgiamoon** [comment]
just to capture the convo here. It's pretty standard practice to turn this
off because if we don't it can capture the user's mouse unintentionally. I
think it will be more usable if we disable scrollWheelZoom which if just an
option on the map settings (also easy to change back if it seems to cause
problems).

On Thu, Sep 17, 2015 at 11:08 AM, Gem Barrett notifications@github.com
wrote:

> Hmm I've got some usability concerns about removing this default and
> expected interaction - not seen it interfere with the controls so far, can
> we chat about this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/bq2geojson/issues/70#issuecomment-141116513.

## 

Georgia Bullen
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon
