### ISSUE TITLE
Rethink the title bar on the map

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/bq2geojson#72]
I think we could remove the header bar and just keep some of the controls.

See here what the map embeded on Seattle's page looks like: http://wwwqa.seattle.gov/broadband/broadband-map

Desktop:
![screen shot 2015-09-10 at 10 53 06 am](https://cloud.githubusercontent.com/assets/941210/9791759/b46e8186-57aa-11e5-9b8f-83a23e489903.png)

Mobile:
![screen shot 2015-09-10 at 10 53 18 am](https://cloud.githubusercontent.com/assets/941210/9791764/bbdd2d46-57aa-11e5-9807-6911af585d01.png)

**Comment by gembarrett** [comment]
Removed the header title and intro prompt button (as the section accessible from the side panel kind of does the job anyway). Just working out moving the zoom controls and location info without messing up the other control elements - so far it's like playing Jenga with code.
