### ISSUE TITLE
Match the opacity of the hexes to the map legend

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/bq2geojson#9]
Right now this is most noticeable with the gray for the "insufficient data" hexes where the gray in the legend is much darker than on the map.

**Comment by nkinkade** [comment]
With the exception of the "Insuff. data" legend item, all other hex colors already did match the legend colors (.5).

**Comment by georgiamoon** [comment]
Yes, thanks! I just wrote the feature request poorly.

On Fri, Apr 10, 2015 at 10:08 AM, nkinkade notifications@github.com wrote:

> With the exception of the "Insuff. data" legend item, all other hex colors
> already did match the legend colors (.5).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/bq2geojson/issues/9#issuecomment-91570358.

## 

Georgia Bullen
Senior Data Analyst
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon
